steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [build, -t, 'us-central1-docker.pkg.dev/adk-codelab-2026/nexusdrift/watchtower:latest', -f, 'services/watchtower/Dockerfile', .]
  - name: 'gcr.io/cloud-builders/docker'
    args: [push, 'us-central1-docker.pkg.dev/adk-codelab-2026/nexusdrift/watchtower:latest']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '900s'
